pipeline {
    agent any

    environment {
        AWS_REGION            = "us-east-1"
        AWS_ACCOUNT_ID        = "891377262030"
        ECR_REPO              = "agent_repo"
        EKS_CLUSTER           = "lab-eks"
        IMAGE_TAG             = "frontend" 
        
        // AWS Credentials
        AWS_ACCESS_KEY_ID     = credentials('aws_access_key_id')
        AWS_SECRET_ACCESS_KEY = credentials('aws_secret_access_key')
        AWS_SESSION_TOKEN     = credentials('aws_session_token')
    }

    stages {
        stage("Checkout") {
            steps {
                checkout scm
            }
        }

        stage("Login to AWS ECR") {
            steps {
                sh '''
                    aws ecr get-login-password --region $AWS_REGION \
                    | docker login --username AWS --password-stdin \
                      $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
                '''
            }
        }

        stage("Build Frontend Image") {
            steps {
                dir('Apps/frontend') {
                    sh '''
                        docker build -t $ECR_REPO:$IMAGE_TAG .
                        docker tag $ECR_REPO:$IMAGE_TAG \
                          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
                    '''
                }
            }
        }

        stage("Push Image to ECR") {
            steps {
                
                sh 'docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG'
            }
        }

        stage("Deploy Frontend to EKS") {
            steps {
                sh 'aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER'
                
                dir('kubernetes/frontend') {
                    sh "sed -i 's|:latest|:$IMAGE_TAG|g' deployment.yaml"
                    
                    sh 'kubectl apply -f deployment.yaml'
                    sh 'kubectl apply -f service.yaml' 
                    sh 'kubectl rollout restart deployment/frontend-app'
                }
            }
        }
    }
}
