pipeline {
    agent any

    environment {
        AWS_REGION   = "us-east-1"
        ECR_REGISTRY = "058264399739.dkr.ecr.us-east-1.amazonaws.com"
        ECR_REPO     = "agent_repo"
        IMAGE_TAG    = "n8n"
    }

    stages {

        stage('Login to AWS ECR') {
            steps {
                sh '''
                echo "Logging into ECR..."
                aws ecr get-login-password --region $AWS_REGION \
                    | docker login --username AWS --password-stdin $ECR_REGISTRY
                '''
            }
        }

        stage('Pull Image from ECR') {
            steps {
                sh '''
                echo "Pulling image from ECR..."
                docker pull $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG
                '''
            }
        }

        stage('Deploy to EKS') {
            steps {
                dir('Kubernetes/n8n') {
                    withCredentials([file(credentialsId: 'eks-kubeconfig', variable: 'KUBECONFIG')]) {
                        sh '''
                        echo "Applying Kubernetes manifests..."
                        kubectl apply -f deployment.yaml

                        echo "Updating deployment image..."
                        kubectl set image deployment/n8n-deployment n8n-container=$ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG

                        echo "Waiting for rollout..."
                        kubectl rollout status deployment/n8n-deployment
                        '''
                    }
                }
            }
        }
    }
}