pipeline {
    agent any

    environment {
        AWS_REGION            = "us-east-1"
        AWS_ACCOUNT_ID        = "058264399739"
        ECR_REPO              = "agent_repo"
        EKS_CLUSTER           = "lab-eks"
        IMAGE_TAG             = "n8n"

        AWS_ACCESS_KEY_ID     = credentials('aws_access_key_id')
        AWS_SECRET_ACCESS_KEY = credentials('aws_secret_access_key')
        AWS_SESSION_TOKEN     = credentials('aws_session_token')
    }

    stages {

        stage("Checkout") {
            steps {
                checkout scm
            }
        }

        stage("Login to AWS ECR") {
            steps {
                sh '''
                    echo "Logging into ECR..."
                    aws ecr get-login-password --region $AWS_REGION \
                    | docker login --username AWS --password-stdin \
                      $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
                '''
            }
        }

        stage("Pull n8n Image from ECR") {
            steps {
                sh '''
                    echo "Pulling n8n image..."
                    docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
                '''
            }
        }

        stage("Deploy n8n to EKS") {
            steps {
                sh '''
                    echo "Updating kubeconfig..."
                    aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER
                '''

                dir('Kubernetes/n8n') {
                    sh '''
                        echo "Applying Kubernetes manifests..."
                        kubectl apply -f Deployment.yaml
                        kubectl apply -f Service.yaml

                        echo "Updating deployment image..."
                        kubectl set image deployment/n8n-deployment n8n-container=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG

                        echo "Restarting deployment..."
                        kubectl rollout restart deployment/n8n-deployment
                    '''
                }
            }

            post {
                success {
                    script {
                        echo "Deployment Successful! Fetching status..."

                        sh 'kubectl get pods -o wide'
                        sh 'kubectl get service n8n-service'

                        sh """
                        echo 'n8n URL: http://'\$(kubectl get service n8n-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
                        """
                    }
                }
            }
        }
    }
}